test incorrect commit message

diff --git a/jenkins-x.yml b/jenkins-x.yml
--- a/jenkins-x.yml
+++ b/jenkins-x.yml
@@ -3,21 +3,30 @@ pipelineConfig:
   agent:
     image: nodejs12x
   pipelines:
-    overrides:
-      - pipeline: pullRequest
-        name: npm-install
+    pullRequest:
+      preBuild:
         steps:
-          - sh: npm install
-            name: npm-install
-          - sh: npm run build-prod
-            name: npm-build
-          - sh: npm run lint
-            name: npm-lint
-      - pipeline: release
-        name: npm-install
+          - name: conventionalcommits-check
+            image: aevea/commitsar:latest
+            command: $(commitsar > $CONV_COMMIT_FILE) || { echo 'commit check failed' >> $CONV_COMMIT_ERR_FILE; exit 0; }
+          - name: conventionalcommits-print
+            command: cat $CONV_COMMIT_FILE
+          - name: conventionalcommits-comment
+            command: |
+              if [ -f "$CONV_COMMIT_ERR_FILE" ]; then
+                  jx step pr comment -c "$(echo -e "[Conventional Commits](https://www.conventionalcommits.org): **Check Failed** :cursing_face: \n HASH | ERROR | MSG \n --|--|-- \n $(cat  $CONV_COMMIT_FILE | grep "|" | awk  -F"|" '{printf "%s | %s | %s", $2, $3, $4;} {print ""}' | grep -v -e '^[[:space:]]*$' | tail -n +2 | grep '[[:alnum:]]')")"
+                  exit 1;
+              else
+                 echo 'COMMIT MESSAGE CHECK PASSED!'
+              fi
+    release:
+      setVersion:
         steps:
-          - sh: npm install
-            name: npm-install
-          - sh: npm run build-prod
-            name: npm-build
+          - image: nodejs
+            steps:
+              - comment: so we can retrieve the version in later steps
+                name: next-version
+                sh: jx step next-version --filename package.json
+              - name: tag-version
+                sh: jx step tag --version \$(cat VERSION)
 
