Sonar and conv commit pipelines (#44)
chore: add sonar and conventional commits pipelines

diff --git a/.lighthouse/jenkins-x/conventionalcommits.yaml b/.lighthouse/jenkins-x/conventionalcommits.yaml
--- a/.lighthouse/jenkins-x/conventionalcommits.yaml
+++ b/.lighthouse/jenkins-x/conventionalcommits.yaml
@@ -1,13 +1,10 @@
 apiVersion: tekton.dev/v1beta1
 kind: PipelineRun
 metadata:
-  creationTimestamp: null
   labels:
-    branch: master
     jenkins.io/pipelineType: build
-    owner: jenkins-x-quickstarts
-    repository: node-http
-  name: jenkins-x-quickstarts-node-http-lzpkw-1
+    owner: vitech-team
+  name: jenkins-x-conventionalcommits
 spec:
   pipelineSpec:
     params:
@@ -83,7 +80,6 @@ spec:
             value: $(params.REPO_OWNER)
           - name: REPO_URL
             value: $(params.REPO_URL)
-
         taskSpec:
           params:
             - description: git url to clone
@@ -164,114 +160,61 @@ spec:
             name: ""
             resources:
               requests:
-                cpu: 400m
+                cpu: 200m
                 memory: 512Mi
             volumeMounts:
               - mountPath: /home/jenkins
                 name: workspace-volume
+              - mountPath: /home/jenkins/.gnupg
+                name: volume-0
               - mountPath: /etc/podinfo
                 name: podinfo
                 readOnly: true
             workingDir: /workspace/source
           steps:
-            - args:
-                - -c
-                - 'mkdir -p $HOME; git config --global --add user.name $GIT_AUTHOR_NAME; git config --global --add user.email $GIT_AUTHOR_EMAIL; git config --global credential.helper store; git clone $(params.REPO_URL) $(params.subdirectory); echo cloned url: $(params.REPO_URL) to dir: $(params.subdirectory); cd $(params.subdirectory); git checkout $(params.PULL_PULL_SHA); echo checked out revision: $(params.PULL_PULL_SHA) to dir: $(params.subdirectory)'
-              command:
-                - /bin/sh
+            - name: git-clone
               image: gcr.io/jenkinsxio/builder-jx:2.1.32-662
-              name: git-clone
-
               workingDir: /workspace
-            - args:
-                - gitops
-                - git
-                - setup
-                - --namespace
-                - jx-git-operator
-              command:
-                - jx
+              script: |
+                mkdir -p $HOME
+                git config --global credential.helper store
+                git clone $(params.REPO_URL) $(params.subdirectory)
+                echo cloned url: $(params.REPO_URL) to dir: $(params.subdirectory)
+                cd $(params.subdirectory)
+                git checkout $(params.PULL_PULL_SHA)
+                echo checked out revision: $(params.PULL_PULL_SHA) to dir: $(params.subdirectory)
+            - name: git-setup
               image: gcr.io/jenkinsxio/jx-cli:latest
-              name: git-setup
-
               workingDir: /workspace
-            - args:
-                - '[ -d /builder/home ] || mkdir -p /builder && ln -s /tekton/home /builder/home'
-              command:
-                - /bin/sh
-                - -c
+              script: |
+                jx gitops git setup --namespace jx-git-operator
+            - name: git-merge
               image: gcr.io/jenkinsxio/builder-jx:2.1.142-761
-              name: setup-builder-home
-
-            - args:
-                - step
-                - git
-                - merge
-                - --verbose
-                - --baseSHA
-                - $(params.PULL_BASE_SHA)
-                - --sha
-                - $(params.PULL_PULL_SHA)
-                - --baseBranch
-                - $(params.PULL_BASE_REF)
-              command:
-                - jx
-              image: gcr.io/jenkinsxio/builder-jx:2.1.142-761
-              name: git-merge
-
-            - args:
-                - gitops
-                - variables
-              command:
-                - jx
-              image: gcr.io/jenkinsxio/jx-cli:latest
-              name: jx-variables
-
-            - args:
-                - jx step credential -s npm-token -k file -f /builder/home/.npmrc --optional=true
-              command:
-                - /bin/sh
-                - -c
-              image: gcr.io/jenkinsxio/builder-nodejs12x:latest
-              name: build-npmrc
-
-            - args:
-                - npm install
-              command:
-                - /bin/sh
-                - -c
-              image: gcr.io/jenkinsxio/builder-nodejs12x:latest
-              name: build-npm-install
-
-            - args:
-                - CI=true DISPLAY=:99 npm test
-              command:
-                - /bin/sh
-                - -c
-              image: gcr.io/jenkinsxio/builder-nodejs12x:latest
-              name: build-npm-test
-
-            - name: build-npm-prod
-              script: npm run build-prod
-              image: gcr.io/jenkinsxio/builder-nodejs12x:latest
-
-            - args:
-                - source .jx/variables.sh && /kaniko/executor $KANIKO_FLAGS --cache=true --cache-dir=/workspace --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION --cache-repo=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/cache
-              command:
-                - /busybox/sh
-                - -c
-              image: gcr.io/kaniko-project/executor:debug-v0.24.0
-              name: build-container-build
-
-            - args:
-                - source /workspace/source/.jx/variables.sh && jx preview create
-              command:
-                - /bin/bash
-                - -c
-              image: gcr.io/jenkinsxio/jx-cli:latest
-              name: promote-jx-preview
-
+              script: |
+                jx step git merge --verbose \
+                  --baseSHA $(params.PULL_BASE_SHA) --sha $(params.PULL_PULL_SHA) --baseBranch $(params.PULL_BASE_REF)
+            - name: conventionalcommits-check
+              image: aevea/commitsar:latest
+              script: |
+                $(commitsar > commit.check 2> commit.check.failed) \
+                  || { echo 'commit check failed' >> check.failed ; exit 0; }
+            - name: conventionalcommits-print
+              image: aevea/commitsar:latest
+              script: |
+                cat commit.check
+            - name: conventionalcommits-comment
+              image: gcr.io/jenkinsxio/builder-gradle5-java11:latest
+              script: |
+                if [ -f "$CONV_COMMIT_ERR_FILE" ]; then
+                    jx step pr comment -c "$(echo -e "[Conventional Commits](https://www.conventionalcommits.org): **Check Failed** :cursing_face: \n HASH | ERROR | MSG \n --|--|-- \n $(cat  $CONV_COMMIT_FILE | grep "|" | awk  -F"|" '{printf "%s | %s | %s", $2, $3, $4;} {print ""}' | grep -v -e '^[[:space:]]*$' | tail -n +2 | grep '[[:alnum:]]')")"
+                    exit 1;
+                else
+                   echo 'COMMIT MESSAGE CHECK PASSED!'
+                fi
           volumes:
+            - name: volume-0
+              secret:
+                secretName: jenkins-release-gpg
             - emptyDir: { }
               name: workspace-volume
             - downwardAPI:
@@ -285,4 +228,4 @@ spec:
     hostNetwork: false
     schedulerName: ""
   serviceAccountName: tekton-bot
-  timeout: 30m
+  timeout: 240h0m0s
